packages = ["regex"]
[files] 
"/textAnalysis/morphophonologyclitics_generate.hfstol" = "./morphophonologyclitics_generate.hfstol"
"/textAnalysis/morphophonologyclitics_generate_mcor_spelling.hfstol" = "./morphophonologyclitics_generate_mcor_spelling.hfstol"
"/textAnalysis/morphophonologyclitics_generate_unsyncopated.hfstol" = "./morphophonologyclitics_generate_unsyncopated.hfstol"
"/textAnalysis/morphophonologyclitics_analyze_mcor_spelling.hfstol" = "./morphophonologyclitics_analyze_mcor_spelling.hfstol"
"/textAnalysis/languageSpecificAuxiliaryFiles/otw/pos_glosses/pos_regex.txt" = "./pos_regex.txt"
"/textAnalysis/pure_python_basic_text.py" = "./pure_python_basic_text.py"
"/textAnalysis/pure_python_analysis.py" = "./pure_python_analysis.py"
"/textAnalysis/conjugator.py" = "./conjugator.py"
"/textAnalysis/trie.py" = "./trie.py"
"/textAnalysis/nish_trie.py" = "./nish_trie.py"
"/textAnalysis/nish_pos.py" = "./nish_pos.py"

