abbreviations = {
        "VAI": "Intransitive Verb with an Animate subject (description/action of a being or remarkable thing)",
        "VAIO": "'Intransitive' Verb with an Animate subject and an Object (action performed by a being or remarkable thing to something else)",
        "VII": "Intransitive Verb with an Inanimate subject (description/action of a thing)",
        "VTA": "Transitive Verb with an Animate object (action performed on a being or remarkable thing)",
        "VTI": "Transitive Verb with an Inanimate object (action performed on a thing)",
        "Cnj": "Conjunct order (used in questions, relative clauses, if-then statements)",
        "Itr": "Iterative (marks repeated actions)",
        "Imp": "Imperative order (used in commands)",
        "Pcp": "Participle (relative clauses: they who X)",
        "Cmpd": "Compound (two words joined to make a bigger word)",
        "1": "First person  (I/me/my...)",
        "2": "Second person  (you/your...)",
        "3": "Third person  (he/she/him/her/his/hers...)",
        "Obv": "Obviation  (a way of distinguishing third persons from each other. The obviated third person is backgrounded/less central)",
        "ObvPlus": "Futher obviative  (a way of distinguishing backgrounded third persons from each other)",
        "X": "Unspecified person (when prefixed: someone's X, when suffixed, I was X'ed (by someone), in Nishnaabemwin 'by someone' cannot be added)",
        "0": "Inanimate (it, a thing)",
        "Ext": "Extended (the person prefix ni/gi/o- has been extended with da/di/doo)",
        "Nul": "Null (the syncope expected with person prefix o- did not occur, as if no prefix had been added)",
        "1Pl": "First person plural (we/us/our)",
        "21Pl": "First person plural inclusive (we/us/our ... including you)",
        "2Pl": "Second person plural (youse/youse's)",
        "3Pl": "Third person plural (they/them/theirs)",
        "3Obv": "Third person obviative (the other one, disambiguation of third persons)",
        "3ObvPlus": "Third person further obviative (the other _other_ one, disambiguation of third persons)",
        "0Pl": "Inanimate plural (many things)",
        "0Obv": "Inanimate obviative (the other thing, disambiguation of inanimate third persons)",
        "Neg": "Negative (not)",
        "Pl": "Plural (more than one)",
        "Prt": "Preterit (in verbs: X has been completed, in nouns: X is broken/deceased/no longer)",
        "Dub": "Dubitative (speaker doubts/needs to infer that X)",
        "Voc": "Vocative (calling to X)",
        "Loc": "Locative (on/in/at X)",
        "DistLoc": "Distributed locative (around/among X)",
        "Redup": "Reduplication (indicates intensity, repetitiveness, plurality of subject, etc)",
        "ThmDir": "Direct theme [Y Xs him/her] ('-aa', marks third person object for VTAs (prefix is subject), often called a 'direct non-local theme')",
        "Thm1": "First person theme [you X me] ('-i' (often deleted), marks second person subject and first person object for VTAs (prefix is subject), often called a 'direct local theme')",
        "Thm1Pl2": "Second person first plural theme [we X you] ('-igoo', marks first person plural subject and second person object for VTAs (prefix is object), often called an 'indirect local theme')",
        "Thm2": "Second person theme [I X you] ('-in', marks first person singular subject and second person object for VTAs (prefix is object), often called an 'indirect local theme')",
        "ThmInv": "Inverse theme [he/she/it X's Y] ('-igo/ig', marks third person/inanimate subject for VTAs (prefix is object), often called an 'indirect local theme')",
        "ThmPas": "Passive theme [Y is X'ed] ('-igoo/aa/ind', marks passive voice (prefix is patient) for VAIs derived from VTAs, often called an 'unspecified actor theme')",
        #"Thm1": "Conjunct order first person theme [Y Xs me] ('-i', marks first person object for conjunct order VTAs)",
        "Thm2a": "Conjunct order second person theme A [I X you] ('-inin', marks second person object, non-third person subject for conjunct order VTAs)",
        "Thm2b": "Conjunct order second person theme B [He/she X's you] ('-ik', marks second person object, third person subject for conjunct order VTAs)",
        "ThmNul": "Conjunct order third person theme [I/you X him/her] ('--', marks third person object, non-third person subject for conjunct order VTAs)",
        "Rflx": "Reflexive (A does X to A's self)",
        "Rcpl": "Reciprocal (A and B do X to each other)",
        "Caus": "Causative (A makes B do X)",
        "Benef": "Benefactive (A X's for B)",
        "Poss": "Verb of possession (A owns B)",
        "Pass": "Passive verb (A is X'ed)",
        "AntPass": "Antipassive verb (A X's (B), aka actor-focus)",
        "NA": "Animate Noun (a being or remarkable thing)",
        "NI": "Inanimate Noun (a thing)",
        "NAD": "Dependent Animate Noun (an obligatorily posessed being or remarkable thing)",
        "NID": "Dependent Inanimate Noun (an obligatorily posessed thing)",
        "Con": "Contemptive (dislike/disdain/teasing for X)",
        "Dim": "Diminutive (cuteness/smallness/affection for X)",
        "Pej": "Pejorative (stronger dislike for X)",
        "ThmPos": "Posessive theme (marks some possessed nouns)",
        "Imm": "Immediate ('do it now!')",
        "Del": "Delayed ('do it in a while!')",
        "Conj": "Conjunction (and, or, but)",
        "Interj": "Interjection (ah!)",
        "Num": "Numeral (1,2,3...)",
        "Pron": "Pronoun (I/you/that...)",
        "Ipc": "Independent particle (the 'other' category)",
        "Qnt": "Quantifier (some/all/most...)",
        "Adv": "Adverbial",
        "Else": "Something that resisted analysis as a full form",
        "PV/CCNJ": "Changed conjunct form",
        #"PV/...": "A preverb"
        }

abbreviations_high = {
        "VAI": "Intransitive Verb with an Animate subject (description/action of a being or remarkable thing)",
        "VAIO": "'Intransitive' Verb with an Animate subject and an Object (action performed by a being or remarkable thing to something else)",
        "VII": "Intransitive Verb with an Inanimate subject (description/action of a thing)",
        "VTA": "Transitive Verb with an Animate object (action performed on a being or remarkable thing)",
        "VTI": "Transitive Verb with an Inanimate object (action performed on a thing)",
        "Cnj": "Conjunct order (used in questions, relative clauses, if-then statements)",
        "S": "Subject",
        "O": "Object",
        "Pos": "Possessor",
        "Itr": "Iterative (marks repeated actions)",
        "Imp": "Imperative order (used in commands)",
        "Pcp": "Participle (relative clauses: they who X)",
        "(Focus:O)": "Relative clause focused on the object (In English: the dogs that man bit)",
        "(Focus:S)": "Relative clause focused on the subject (In English: the man that bit the dogs)",
        "(Focus:3Pl)": "Relative clause focused on 3Pl (In English: they that bit the man, or, they that the man bit.)",
        "(Focus:3Obv)": "Relative clause focused on 3Obv (Roughly in English: the one that the dog chased, or, the one that chased the dog)",
        "1": "First person  (I/me/my...)",
        "1Pl": "First person plural (we/us/our)",
        "21Pl": "First person plural inclusive (we/us/our...including you)",
        "2": "Second person  (you/your...)",
        "2Pl": "Second person plural (youse/youse's)",
        "3": "Third person  (he/she/him/her/his/hers...)",
        "3Obv": "Obviative (the other one, used to mark a third person as more in the background than another)",
        "3ObvPlus": "Third person further obviative (the other _other_ one, disambiguation of third persons)",
        "3Pl": "Third person plural (they/them/theirs)",
        "Obv": "Obviative  (a way of distinguishing third persons from each other. The obviated third person is backgrounded/less central)",
        "ObvPlus": "Futher obviative (a way of distinguishing backgrounded third persons from each other)",
        "X": "Unspecified person (on nouns: someone's X, on verbs: I was X'ed (by someone); in Nishnaabemwin 'by someone' cannot be added)",
        "0": "Inanimate (it, a thing)",
        "0Pl": "Inanimate plural (many things)",
        "0Obv": "Inanimate obviative (the other thing, disambiguation of inanimate third persons)",
        "Ext": "Extended (the person prefix ni/gi/o has been extended with da/di/doo)",
        "Nul": "Null (the syncope expected with a person prefix did not occur, as if no prefix had been added)",
        "Neg": "Negative (not)",
        "Pl": "Plural (more than one)",
        "Prt": "Preterit (on verbs: X has been completed, on nouns: X is broken/deceased/no longer)",
        "Dub": "Dubitative (speaker doubts/needs to infer that X)",
        "Voc": "Vocative (calling to X)",
        "Loc": "Locative (on/in/at X)",
        "DistLoc": "Distributed locative (around/among X)",
        "Redup": "Reduplication (indicates intensity, repetitiveness, plurality of subject, etc)",
        "ThmPas": "Passive theme [Y is X'ed] ('-igoo/aa/ind', marks passive voice (prefix is patient) for VAIs derived from VTAs, often called an 'unspecified actor theme')",
        "Rflx": "Reflexive (A does X to A's self)",
        "Rcpl": "Reciprocal (A and B do X to each other)",
        "Caus": "Causative (A makes B do X)",
        "Benef": "Benefactive (A X's for B)",
        "Poss": "Verb of possession (A owns B)",
        "Pass": "Passive verb (A is X'ed)",
        "AntPass": "Antipassive verb (A X's (B), aka actor-focus)",
        "NA": "Animate Noun (a being or remarkable thing)",
        "NI": "Inanimate Noun (a thing)",
        "NAD": "Dependent Animate Noun (obligatorily posessed being or remarkable thing)",
        "NID": "Dependent Inanimate Noun (obligatorily posessed thing)",
        "Con": "Contemptive (dislike/disdain/teasing for X)",
        "Dim": "Diminutive (cuteness/smallness/affection for X)",
        "Pej": "Pejorative (stronger dislike for X)",
        #"ThmPos": "Posessive theme (marks some possessed nouns)",
        "Del": "Delayed ('do it in a while!')",
        "Conj": "Conjunction (and, or, but)",
        "Interj": "Interjection (ah!)",
        "Num": "Numeral (1,2,3...)",
        "Pron": "Pronoun (I/you/that...)",
        "Ipc": "Independent particle (the 'other' category)",
        "Qnt": "Quantifier (some/all/most...)",
        "Adv": "Adverbial",
        "Else": "Something that resisted analysis as a full form",
        "PV/CCNJ": "Changed conjunct form",
        #"PV/...": "A preverb"
        "PV": "A preverb",
        "PN": "A prenoun",
        "PA": "A pre-adverb"
        }

ciw_abbreviations = {
        "ADVConj": "A conjunction (and, or, but)",
        "ADVDisc": "A discourse marker (so)",
        "ADVLoc": "An adverb of location (here, there)",
        "ADVGram": "A grammatical adverb",
        "ADVQnt": "A quantifier (some, all, most)",
        "ADVPred": "A predicative adverb",
        "ADVNeg": "A negative adverb (ever, at all)",
        "ADVTmp": "A temporal adverb (then, soon)",
        "ADVMan": "A manner adverb (quickly, thoroughly)",
        "ADVDeg": "A degree adverb (extremely, partially)",
        "ADVDub": "A dubitative adverb",
        "ADVInter": "An interrogative adverb",
        "NAD": "Dependent Animate Noun (an obligatorily posessed being or remarkable thing)",
        "NA": "Animate Noun (a being or remarkable thing)",
        "NI": "Inanimate Noun (a thing)",
        "NID": "Dependent Inanimate Noun (an obligatorily posessed thing)",
        "0": "?", #what is this? it occurs in the lists labeled Dim, Poss, Pej, Pret, PersPoss. Perhaps not a tag, just the empty symbol, marking optional info
        #"Con": "Contemptive (dislike/disdain/teasing for X)", #I don't see anything for contemptives!
        "Dim": "Diminutive (cuteness/smallness/affection for X)",
        "Pej": "Pejorative (stronger dislike for X)",
        "Poss": "Posessive theme (marks some possessed nouns)", #I assume this is right
        "Pret": "Preterit (on verbs: X has been completed, on nouns: X is broken/deceased/no longer)",
        "Loc": "Locative (on/in/at X)",
        "LocDist": "Distributed locative (around/among X)",
        "ProxSg" : "Proximal singular (one entity, a third person that has not been backgrounded by being obviated)",
        "ObvPl" : "Obviative plural (the other ones, third persons that are more in the background)", #I thought number was collapsed w/obviatives
        "ProxPl": "Proximal plural (more than one entity that has not been backgrounded by being obviated)",
        "ObvSg": "Obviative singular (the other one, a third person that has been backgrounded)",
        "Pl": "Plural (more than one)", #how is this working? we already have obv/prox pl/sg
        "Sg": "Singular (one entity)",
        "Voc": "Vocative (calling to X)",
        "1Sg": "First person singular (I)", #not on nouns, just pronouns
        "1SgPoss": "First person singular possessive (mine)",
        "Excl": "First person plural exclusive (us ... not you)", #not on nouns, just pronouns
        "Incl": "First person plural inclusive (us and you)", #not on nouns, just pronouns
        "ExclPoss": "First person plural exclusive possessive (ours ... not yours)",
        "InclPoss": "First person plural inclusive possessive (ours and yours)",
        "2Pl": "Second person plural (youse)", #not on nouns, just pronouns
        "2PlPoss": "Second person plural possessive (youse's)",
        "2Sg": "Second person singular (you)", #not on nouns, just pronouns
        "2SgPoss": "Second person singular possessive (your)",
        "3Obv": "Third person obviative (the other one, disambiguation of third persons)",
        "3ObvPlus": "Third person further obviative (the other _other_ one, disambiguation of third persons)",
        "3Pl": "Third person plural (the other guys)",  #not on nouns, just pronouns #Obviation not specified!
        "3PlObvPoss": "Third person plural obviative possessive (the other guys's)", #is this formally different from 3SgObvPoss?
        "3PlProxPoss": "Third person plural proximal possessive (theirs)",
        "3Sg": "Third person singular (the other guy)",  #not on nouns, just pronouns #Obviation not specified!
        "3SgObvPoss": "Third person singular obviative possessor (the other guy's)", #is this formally different from 3PlObvPoss?
        "3SgProxPoss": "Third person singular proximal possessive (his/hers)",
        "Num": "Numeral (1,2,3...)", #opd links have adv-num, but not POS tags from the model
        "PCDisc": "Discourse particle",
        "PCAsp": "Aspectual particle",
        "PCEmph": "Emphatic particle",
        "PCInterj": "Interjective particle",
        "PRONDem": "Demonstrative pronoun (that/those)",
        "PRONDub": "Dubitative pronoun",
        "PRONIndf": "Indefinite pronoun (a/some)",
        "PRONInter": "Interrogative pronoun (who)",
        "PRONPer": "Personal pronoun (I/you/he/him)",
        "PRONPret": "Preterite pronoun",
        "PRONSim": "",
        "NamePlace": "Name of a place",
        "NamePerson": "Name of a person",
        "PVTense/gii": "Past tense (I walked)",
        "VII+Augment/magad": "A common way of making an Intransitive Verb with an Inanimate subject (description/action of a thing)",
        "VAI": "Intransitive Verb with an Animate subject (description/action of a being or remarkable thing)",
        "VAIPL": "Intransitive Verb with only PLural Animate subjects (description/action of beings or remarkable things)",
        "VAIO": "'Intransitive' Verb with an Animate subject and an Object (action performed by a being or remarkable thing to something else)",
        "VII": "Intransitive Verb with an Inanimate subject (description/action of a thing)",
        "VIIPL": "Intransitive Verb with only PLural Inanimate subjects (description/action of things)",
        "VTA": "Transitive Verb with an Animate object (action performed on a being or remarkable thing)",
        "VTI": "Transitive Verb with an Inanimate object (action performed on a thing)",
        }
