packages = [
            #"https://files.pythonhosted.org/packages/eb/f5/3ea71e974dd0117b95a54ab2c79d781b4376d257d91e4c2249605f4a54ae/pyhfst-1.2.0-py2.py3-none-any.whl",
            #"pyhfst>=1.2.0",
            #"emfs://pyhfst-1.2.0-py2.py3-none-any.whl",
            "regex",
            ]
[files] 
"/textAnalysis/morphophonologyclitics_analyze.hfstol" = "./morphophonologyclitics_analyze.hfstol"
"/textAnalysis/morphophonologyclitics_analyze_mcor_spelling.hfstol" = "./morphophonologyclitics_analyze_mcor_spelling.hfstol"
"/textAnalysis/morphophonologyclitics_analyze_unsyncopated.hfstol" = "./morphophonologyclitics_analyze_unsyncopated.hfstol"
"/textAnalysis/morphophonology_analyze_border_lakes.hfstol" = "./morphophonology_analyze_border_lakes.hfstol"
#"/morphophonologyclitics_generate.hfstol" = "./morphophonologyclitics_generate.hfstol"
#"/textAnalysis/morphophonologyclitics_analyze_relaxed_slim.hfstol" = "./morphophonologyclitics_analyze_relaxed_slim.hfstol"
"/textAnalysis/languageSpecificAuxiliaryFiles/otw/pos_glosses/copilot_otw2eng.txt" = "./copilot_otw2eng.txt"
"/textAnalysis/languageSpecificAuxiliaryFiles/otw/pos_glosses/otw2nishID.txt" = "./otw2nishID.txt"
"/textAnalysis/languageSpecificAuxiliaryFiles/otw/pos_glosses/pos_regex.txt" = "./pos_regex.txt"
"/textAnalysis/languageSpecificAuxiliaryFiles/ciw/pos_glosses/pos_regex.txt" = "./ciw_pos_regex.txt"
"/textAnalysis/sentence_complexity.py" = "./sentence_complexity.py"
"/textAnalysis/opd_links.py" = "./opd_links.py"
"/textAnalysis/opd_manual_links.csv" = "./opd_manual_links.csv"
