packages = [
            #"https://files.pythonhosted.org/packages/eb/f5/3ea71e974dd0117b95a54ab2c79d781b4376d257d91e4c2249605f4a54ae/pyhfst-1.2.0-py2.py3-none-any.whl",
            #"pyhfst>=1.2.0",
            #"emfs://pyhfst-1.2.0-py2.py3-none-any.whl",
            "regex",
            ]
[files] 
"/textAnalysis/morphophonologyclitics_analyze.hfstol" = "./morphophonologyclitics_analyze.hfstol"
#"/textAnalysis/morphophonologyclitics_generate.hfstol" = "./morphophonologyclitics_generate.hfstol"
"/textAnalysis/morphophonologyclitics_analyze_relaxed_slim.hfstol" = "./morphophonologyclitics_analyze_relaxed_slim.hfstol"
"/textAnalysis/languageSpecificAuxiliaryFiles/otw/pos_glosses/copilot_otw2eng.txt" = "./copilot_otw2eng.txt"
"/textAnalysis/languageSpecificAuxiliaryFiles/otw/pos_glosses/pos_regex.txt" = "./pos_regex.txt"
"/textAnalysis/alg_morphological_summary.py" = "./alg_morphological_summary.py"
"/textAnalysis/alg_morphological_summary.py" = "./alg_morphological_summary.py"
"/textAnalysis/amalgamate_for_review.py"     = "./amalgamate_for_review.py"
"/textAnalysis/contextualize.py"             = "./contextualize.py"
"/textAnalysis/engdict.py"                   = "./engdict.py"
"/textAnalysis/false_negative_triage.py"     = "./false_negative_triage.py"
"/textAnalysis/generate_alts.py"             = "./generate_alts.py"
"/textAnalysis/glossarygen.py"               = "./glossarygen.py"
"/textAnalysis/grammar_codes.py"             = "./grammar_codes.py"
"/textAnalysis/interlineargen.py"            = "./interlineargen.py"
"/textAnalysis/json_encoder.py"              = "./json_encoder.py"
"/textAnalysis/lemmatize.py"                 = "./lemmatize.py"
"/textAnalysis/morphosyntactic_summary.py"   = "./morphosyntactic_summary.py"
"/textAnalysis/needleman.py"                 = "./needleman.py"
"/textAnalysis/parse.py"                     = "./parse.py"
"/textAnalysis/performance.py"               = "./performance.py"
"/textAnalysis/postprocess.py"               = "./postprocess.py"
"/textAnalysis/preprocess.py"                = "./preprocess.py"
"/textAnalysis/readwrite.py"                 = "./readwrite.py"
"/textAnalysis/web_lemmatize.py"             = "./web_lemmatize.py"
"/textAnalysis/word_per_line.py"             = "./word_per_line.py"
