packages = [
            "regex",
            ]
[files] 
"/textAnalysis/languageSpecificAuxiliaryFiles/otw/lemmatizations/corbiere_lemmatized_corpus_20241210.py" = "./corbiere_lemmatized_corpus_20241210.py"
